FROM node:20 as builder

ARG VITE_BACKEND_URL
ARG VITE_MATOMO_SITE_ID
ARG VITE_BACKEND_URL
ARG VITE_SENTRY_DSN
ARG VITE_SENTRY_SAMPLE_RATE

COPY . /build
WORKDIR /build

# Prevent vite build OOM
ENV NODE_OPTIONS="--max-old-space-size=4096"
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_MATOMO_SITE_ID=$VITE_MATOMO_SITE_ID
ENV VITE_BACKEND_URL=$VITE_BACKEND_URL
ENV VITE_SENTRY_DSN=$VITE_SENTRY_DSN
ENV VITE_SENTRY_SAMPLE_RATE=$VITE_SENTRY_SAMPLE_RATE

RUN yarn install --frozen-lockfile && yarn build

FROM nginx:stable

COPY --from=builder /build/dist /usr/share/nginx/html
