import type { BlockDefinition } from "../types";
import { testBoards, testStatement } from "../utils";

const ledstripDemoOptions = [
	["%{BKY_LEAPHY_LED_STRIP_LIGHTBANK}", "0"],
	["%{BKY_LEAPHY_LED_STRIP_BREATHE}", "1"],
	["%{BKY_LEAPHY_LED_STRIP_GULF}", "3"],
	["%{BKY_LEAPHY_LED_STRIP_RAINBOW}", "4"],
	["%{BKY_LEAPHY_LED_STRIP_COLORGULF}", "5"],
];

function getDisplayBlocks(
	prefix: string,
	translatePrefix: string,
	lines: number,
): BlockDefinition[] {
	const displayLines = new Array(lines)
		.fill(null)
		.map((_, index) => [(index + 1).toString(), index.toString()]);

	return [
		{
			type: `${prefix}_clear`,
			message0: `%%{${translatePrefix}_CLEAR}`,
			previousStatement: null,
			nextStatement: null,
			style: "leaphy_blocks",
			helpUrl: "",
			test: testStatement(prefix),
			aiHelp: `Clear the ${translatePrefix} display`,
			relevanceKey: `${translatePrefix}_DISPLAY`,
		},
		{
			type: `${prefix}_set_text_size`,
			message0: `%%{${translatePrefix}_SET_TEXT_SIZE} %1`,
			args0: [{ type: "input_value", name: "NUM", check: "Number" }],
			inputsInline: true,
			previousStatement: null,
			nextStatement: null,
			style: "leaphy_blocks",
			helpUrl: "",
			test: testStatement(prefix),
			aiHelp: `Set the text size on the ${translatePrefix} display`,
			relevanceKey: `${translatePrefix}_DISPLAY`,
		},
		{
			type: `${prefix}_print_line`,
			message0: `%%{${translatePrefix}_PRINT} %1 %2 %3`,
			args0: [
				{ type: "input_dummy" },
				{
					type: "field_dropdown",
					name: "DISPLAY_ROW",
					options: displayLines,
				},
				{ type: "input_value", name: "VALUE" },
			],
			inputsInline: true,
			previousStatement: null,
			nextStatement: null,
			style: "leaphy_blocks",
			helpUrl: "",
			test: testStatement(prefix),
			aiHelp: `Print the value to the ${translatePrefix} display on a selected row`,
			relevanceKey: `${translatePrefix}_DISPLAY`,
		},
		{
			type: `${prefix}_print_value`,
			message0: `%%{${translatePrefix}_PRINT} %1 %2 %3 = %4 %5`,
			args0: [
				{ type: "input_dummy" },
				{
					type: "field_dropdown",
					name: "DISPLAY_ROW",
					options: displayLines,
				},
				{ type: "input_value", name: "NAME" },
				{ type: "input_dummy" },
				{ type: "input_value", name: "VALUE" },
			],
			inputsInline: true,
			previousStatement: null,
			nextStatement: null,
			style: "leaphy_blocks",
			helpUrl: "",
			test: testStatement(prefix),
			aiHelp: `Print the value with name to the ${translatePrefix} display on a selected row`,
			relevanceKey: `${translatePrefix}_DISPLAY`,
		},
		{
			type: `${prefix}_display`,
			message0: `%%{${translatePrefix}_DISPLAY}`,
			previousStatement: null,
			nextStatement: null,
			style: "leaphy_blocks",
			helpUrl: "",
			test: testStatement(prefix),
			aiHelp: `Display the changed values on the ${translatePrefix} display`,
			relevanceKey: `${translatePrefix}_DISPLAY`,
		},
	];
}

export const testConfig = testBoards({ sd: ["l_nano"] });
export const blocks: BlockDefinition[] = [
	{
		type: "leaphy_io_digitalwrite",
		message0: "%%{BKY_ARD_DIGITALWRITE} %1 %%{BKY_ARD_WRITE_TO} %2",
		args0: [
			{
				type: "field_pin_selector",
				name: "PIN",
				mode: "digital",
			},
			{ type: "input_value", name: "STATE", check: "Boolean" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("general"),
		helpUrl: "http://arduino.cc/en/Reference/DigitalWrite",
		aiHelp: "Write the digital value to a selected pin (automatic mode select)",
	},
	{
		type: "leaphy_io_analogwrite",
		message0: "%%{BKY_ARD_ANALOGWRITE} %1 %%{BKY_ARD_WRITE_TO} %2",
		args0: [
			{ type: "field_pin_selector", name: "PIN", mode: "pwm" },
			{ type: "input_value", name: "NUM", check: "Number" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("general"),
		helpUrl: "http://arduino.cc/en/Reference/AnalogWrite",
		aiHelp:
			"Write the analog value (pwm) to a selected pin (automatic mode select)",
	},
	{
		type: "leaphy_serial_print_line",
		message0: "%%{BKY_LEAPHY_SERIAL_PRINT} %1 %2",
		args0: [{ type: "input_dummy" }, { type: "input_value", name: "VALUE" }],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl: "",
		test: testStatement("general"),
		aiHelp: "Print the value to the serial port",
	},
	{
		type: "leaphy_serial_print_value",
		message0: "%%{BKY_LEAPHY_SERIAL_PRINT} %1 %2 = %3 %4",
		args0: [
			{ type: "input_dummy" },
			{ type: "input_value", name: "NAME" },
			{ type: "input_dummy" },
			{ type: "input_value", name: "VALUE" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl: "",
		test: testStatement("general"),
		aiHelp: "Print the value with name to the serial port",
	},
	{
		type: "leaphy_servo_write",
		message0:
			"%%{BKY_ARD_SERVO_WRITE} %1 %2 %%{BKY_ARD_SERVO_WRITE_TO} %3 %%{BKY_ARD_SERVO_WRITE_DEG_180}",
		args0: [
			{
				type: "field_pin_selector",
				name: "SERVO_PIN",
				mode: "digital",
			},
			{ type: "input_dummy" },
			{ type: "input_value", name: "SERVO_ANGLE", check: "Number" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("general"),
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=TT%20motors-,Servo%20motors,-Rotating%20servo%20motor",
		aiHelp: "Write the servo angle to a selected pin",
	},
	{
		type: "leaphy_multiplexer_digitalwrite",
		message0: "%%{BKY_ARD_SET_MULTIPLEXER} %1",
		args0: [
			{
				type: "field_dropdown",
				name: "PIN",
				options: [
					["Y0", "0"],
					["Y1", "1"],
					["Y2", "2"],
					["Y3", "3"],
					["Y4", "4"],
					["Y5", "5"],
					["Y6", "6"],
					["Y7", "7"],
				],
			},
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		test: testStatement("extra"),
		style: "leaphy_blocks",
		aiHelp: "Write the digital value to a selected pin on the multiplexer",
	},

	{
		type: "leaphy_led_set_strip",
		message0:
			"%%{BKY_LEAPHY_LED_SET_STRIP} %1 %%{BKY_LEAPHY_LED_SET_PIN} %2 %%{BKY_LEAPHY_LED_SET_LEDS} %3",
		args0: [
			{ type: "input_dummy" },
			{ type: "input_value", name: "LED_SET_PIN", check: "Number" },
			{ type: "input_value", name: "LED_SET_LEDS", check: "Number" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Potmeter-,Multiple%20leds%C2%A0,-Led%20matrix%C2%A0",
		test: testStatement("ledstrip"),
		relevanceKey: "LED_STRIP",
	},
	{
		type: "leaphy_led_set_basic",
		message0:
			"%%{BKY_LEAPHY_LED_BASIC_LED} %1 %%{BKY_LEAPHY_LED_BASIC_RED} %2 %%{BKY_LEAPHY_LED_BASIC_GREEN} %3 %%{BKY_LEAPHY_LED_BASIC_BLUE} %4",
		args0: [
			{ type: "input_value", name: "LED_SET_LED", check: "Number" },
			{ type: "input_value", name: "LED_BASIC_RED", check: "Number" },
			{ type: "input_value", name: "LED_BASIC_GREEN", check: "Number" },
			{ type: "input_value", name: "LED_BASIC_BLUE", check: "Number" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Oled%20display-,RGB%20led,-Potmeter",
		test: testStatement("ledstrip"),
		relevanceKey: "LED_STRIP",
	},
	{
		type: "leaphy_led_strip_demo",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Potmeter-,Multiple%20leds%C2%A0,-Led%20matrix%C2%A0",
		message0: "%%{BKY_LEAPHY_LED_STRIP_DEMO} %1 %2 %3 %4 %5",
		args0: [
			{
				type: "field_dropdown",
				name: "DEMO_TYPE",
				options: ledstripDemoOptions,
			},
			{ type: "input_dummy" },
			{
				type: "input_value",
				name: "LED_STRIP_DEMO_RED",
				check: "Number",
			},
			{
				type: "input_value",
				name: "LED_STRIP_DEMO_GREEN",
				check: "Number",
			},
			{
				type: "input_value",
				name: "LED_STRIP_DEMO_BLUE",
				check: "Number",
			},
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("ledstrip"),
		aiHelp: "Run a demo on the LED strip",
		relevanceKey: "LED_STRIP",
	},
	{
		type: "leaphy_led_set_speed",
		message0: "%%{BKY_LEAPHY_LED_SET_SPEEDVALUE} %1",
		args0: [
			{
				type: "input_value",
				name: "LED_SET_SPEEDVALUE",
				check: "Number",
			},
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Oled%20display-,RGB%20led,-Potmeter",
		test: testStatement("ledstrip"),
		relevanceKey: "LED_STRIP",
	},

	...getDisplayBlocks("leaphy_display", "BKY_LEAPHY_DISPLAY", 3),

	...getDisplayBlocks("leaphy_display_large", "BKY_LEAPHY_DISPLAY_LARGE", 6),

	{
		type: "leaphy_lcd_clear",
		message0: "%{BKY_LEAPHY_LCD_CLEAR}",
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl: "",
		test: testStatement("lcd"),
		aiHelp: "Clear the I2C LCD display",
		relevanceKey: "LEAPHY_LCD_DISPLAY",
	},
	{
		type: "leaphy_lcd_print_line",
		message0: "%{BKY_LEAPHY_LCD_PRINT} %1 %2 %3",
		args0: [
			{ type: "input_dummy" },
			{
				type: "field_dropdown",
				name: "DISPLAY_ROW",
				options: [
					["1", "0"],
					["2", "1"],
				],
			},
			{ type: "input_value", name: "VALUE" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl: "",
		test: testStatement("lcd"),
		aiHelp: "Print the value to the I2C LCD display on a selected row",
		relevanceKey: "LEAPHY_LCD_DISPLAY",
	},
	{
		type: "leaphy_lcd_print_value",
		message0: "%{BKY_LEAPHY_LCD_PRINT} %1 %2 %3 = %4 %5",
		args0: [
			{ type: "input_dummy" },
			{
				type: "field_dropdown",
				name: "DISPLAY_ROW",
				options: [
					["1", "0"],
					["2", "1"],
				],
			},
			{ type: "input_value", name: "NAME" },
			{ type: "input_dummy" },
			{ type: "input_value", name: "VALUE" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl: "",
		test: testStatement("lcd"),
		aiHelp:
			"Print the value with name to the I2C LCD display on a selected row",
		relevanceKey: "LEAPHY_LCD_DISPLAY",
	},
	{
		type: "leaphy_lcd_set_backlight",
		message0: "%{BKY_LEAPHY_LCD_SET_BACKLIGHT} %1",
		args0: [
			{
				type: "field_dropdown",
				name: "BACKLIGHT",
				options: [
					["%{BKY_LEAPHY_LCD_BACKLIGHT_ON}", "ON"],
					["%{BKY_LEAPHY_LCD_BACKLIGHT_OFF}", "OFF"],
				],
			},
		],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl: "",
		test: testStatement("lcd"),
		aiHelp: "Turn the backlight of the I2C LCD display on or off",
		relevanceKey: "LEAPHY_LCD_DISPLAY",
	},

	{
		type: "leaphy_matrix_init",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Multiple%20leds-,Led%20matrix%C2%A0,-Speaker%C2%A0",
		message0: "%{BKY_LEAPHY_MATRIX_INIT}",
		args0: [
			{ type: "field_pin_selector", name: "DIN", mode: "digital" },
			{ type: "field_pin_selector", name: "CLK", mode: "digital" },
			{ type: "field_pin_selector", name: "CS", mode: "digital" },
		],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("matrix"),
		aiHelp: "Initialize the 8x8 LED matrix",
		relevanceKey: "LED_MATRIX",
	},
	{
		type: "leaphy_matrix_fill",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Multiple%20leds-,Led%20matrix%C2%A0,-Speaker%C2%A0",
		message0: "%{BKY_LEAPHY_MATRIX_FILL}",
		args0: [
			{ type: "input_dummy" },
			{ type: "field_bitmap", name: "MATRIX", width: 8, height: 8 },
		],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("matrix"),
		aiHelp: "Fill the 8x8 LED matrix with a selected pattern",
		relevanceKey: "LED_MATRIX",
	},
	{
		type: "leaphy_matrix_set",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Multiple%20leds-,Led%20matrix%C2%A0,-Speaker%C2%A0",
		message0: "%{BKY_LEAPHY_MATRIX_SET}",
		args0: [
			{ type: "input_value", name: "X", check: "Number" },
			{ type: "input_value", name: "Y", check: "Number" },
			{ type: "input_value", name: "ON", check: "Boolean" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("matrix"),
		aiHelp: "Set a pixel on the 8x8 LED matrix at a selected position",
		relevanceKey: "LED_MATRIX",
	},
	{
		type: "leaphy_matrix_set_brightness",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Multiple%20leds-,Led%20matrix%C2%A0,-Speaker%C2%A0",
		message0: "%{BKY_LEAPHY_MATRIX_SET_BRIGHTNESS}",
		args0: [{ type: "input_value", name: "BRIGHTNESS", check: "Number" }],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("matrix"),
		aiHelp: "Set the brightness of the 8x8 LED matrix",
		relevanceKey: "LED_MATRIX",
	},
	{
		type: "leaphy_matrix_clear",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Multiple%20leds-,Led%20matrix%C2%A0,-Speaker%C2%A0",
		message0: "%{BKY_LEAPHY_MATRIX_CLEAR}",
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("matrix"),
		aiHelp: "Clear the 8x8 LED matrix",
		relevanceKey: "LED_MATRIX",
	},

	{
		type: "leaphy_segment_init",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=%C2%A0Single%20leds-,Segment%20display%C2%A0,-Oled%20display",
		message0: "%{BKY_LEAPHY_SEGMENT_INIT}",
		args0: [
			{ type: "field_pin_selector", name: "CLK", mode: "digital" },
			{ type: "field_pin_selector", name: "DIO", mode: "digital" },
		],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("segment"),
		aiHelp: "Initialize the 4 digit segment display",
		relevanceKey: "SEGMENT_DISPLAY",
	},
	{
		type: "leaphy_segment_set",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=%C2%A0Single%20leds-,Segment%20display%C2%A0,-Oled%20display",
		message0: "%{BKY_LEAPHY_SEGMENT_SET}",
		args0: [{ type: "input_value", name: "NUM", check: "Number" }],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("segment"),
		aiHelp: "Set the value on the 4 digit segment display",
		relevanceKey: "SEGMENT_DISPLAY",
	},
	{
		type: "leaphy_segment_clear",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=%C2%A0Single%20leds-,Segment%20display%C2%A0,-Oled%20display",
		message0: "%{BKY_LEAPHY_SEGMENT_CLEAR}",
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("segment"),
		aiHelp: "Clear the segment display",
		relevanceKey: "SEGMENT_DISPLAY",
	},
	{
		type: "leaphy_segment_set_brightness",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=%C2%A0Single%20leds-,Segment%20display%C2%A0,-Oled%20display",
		message0: "%{BKY_LEAPHY_SEGMENT_SET_BRIGHTNESS}",
		args0: [{ type: "input_value", name: "BRIGHTNESS", check: "Number" }],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("segment"),
		aiHelp: "Set the brightness of the segment display",
		relevanceKey: "SEGMENT_DISPLAY",
	},

	{
		type: "leaphy_sound_init",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Led%20matrix-,Speaker%C2%A0,-Stichting",
		message0: "%{BKY_LEAPHY_SOUND_INIT}",
		args0: [
			{ type: "field_pin_selector", name: "RX", mode: "digital" },
			{ type: "field_pin_selector", name: "TX", mode: "digital" },
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("speaker"),
		aiHelp: "Initialize the speaker (RedMP3 module)",
		relevanceKey: "REDMP3_MODULE",
	},
	{
		type: "leaphy_sound_play",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Led%20matrix-,Speaker,-Stichting",
		message0: "%{BKY_LEAPHY_SOUND_PLAY}",
		args0: [{ type: "input_value", name: "ITEM", check: "Number" }],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("speaker"),
		aiHelp: "Play a sound from the RedMP3 module",
		relevanceKey: "REDMP3_MODULE",
	},
	{
		type: "leaphy_sound_set_volume",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Led%20matrix-,Speaker,-Stichting",
		message0: "%{BKY_LEAPHY_SOUND_SET_VOLUME}",
		args0: [{ type: "input_value", name: "VOLUME", check: "Number" }],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("speaker"),
		aiHelp: "Set the volume of the RedMP3 module",
		relevanceKey: "REDMP3_MODULE",
	},
	{
		type: "leaphy_sound_stop",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Led%20matrix-,Speaker,-Stichting",
		message0: "%{BKY_LEAPHY_SOUND_STOP}",
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("speaker"),
		aiHelp: "Stop the sound from the RedMP3 module",
		relevanceKey: "REDMP3_MODULE",
	},

	{
		type: "i2c_list_devices",
		message0: "%{BKY_I2C_LIST_DEVICES}",
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		helpUrl:
			"https://www.leaphyfoundation.com/tutorials-leaphy-electronics.html#:~:text=Batteries%20and%20power-,I2C%20sensor%20module%C2%A0,-Sensors",
		test: testStatement("general"),
		aiHelp: "List the connected I2C devices on the multiplexer",
	},
	{
		type: "leaphy_sdcard_write",
		message0: "%%{BKY_LEAPHY_SDCARD_WRITE}",
		message1: "%%{BKY_LEAPHY_SDCARD_WRITE_TO_FILE} %1",
		message2: "%%{BKY_LEAPHY_SDCARD_WRITE_VALUE} %1",
		args1: [{ type: "input_value", name: "FILENAME", check: "String" }],
		args2: [{ type: "input_value", name: "VALUE" }],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		tooltip: "CS=10",
		test: testStatement("sd"),
		aiHelp: "Write a value to a file on the SD card",
		relevanceKey: "SD_CARD",
	},
	{
		type: "leaphy_sdcard_remove",
		message0: "%{BKY_LEAPHY_SDCARD_REMOVE}",
		args0: [{ type: "input_value", name: "FILENAME", check: "String" }],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("sd"),
		aiHelp: "Remove a file from the SD card",
		relevanceKey: "SD_CARD",
	},
	{
		type: "leaphy_sdcard_mkdir",
		message0: "%{BKY_LEAPHY_SDCARD_MKDIR}",
		args0: [{ type: "input_value", name: "FILENAME", check: "String" }],
		previousStatement: null,
		nextStatement: null,
		style: "leaphy_blocks",
		test: testStatement("sd"),
		aiHelp: "Create a directory on the SD card",
		relevanceKey: "SD_CARD",
	},
];
