import type { BlockDefinition } from "../types";
import { testStatement } from "../utils";

export const blocks: BlockDefinition[] = [
	{
		type: "time_delay",
		message0: "%{BKY_ARD_TIME_DELAY} %1 %2",
		args0: [
			{ type: "input_value", name: "DELAY_TIME_MILI", check: "Number" },
			{
				type: "field_dropdown",
				name: "UNIT",
				options: [
					["ms", "ms"],
					["μs", "μs"],
					["s", "s"],
				],
			},
		],
		inputsInline: true,
		previousStatement: null,
		nextStatement: null,
		style: "loop_blocks",
		tooltip: "%{BKY_ARD_TIME_DELAY_TIP}",
		helpUrl: "http://arduino.cc/en/Reference/Delay",
		test: testStatement("general"),
	},
	{
		type: "controls_repeat_forever",
		message0: "%{BKY_CONTROLS_REPEAT_FOREVER_TITLE}",
		message1: "%{BKY_CONTROLS_REPEAT_INPUT_DO} %1",
		args1: [{ type: "input_statement", name: "DO" }],
		previousStatement: null,
		nextStatement: null,
		style: "loop_blocks",
		tooltip: "%{BKY_CONTROLS_REPEAT_TOOLTIP}",
		helpUrl: "%{BKY_CONTROLS_REPEAT_HELPURL}",
		test: testStatement("general"),
	},
	{
		type: "controls_if",
		message0: "%{BKY_CONTROLS_IF_MSG_IF} %1 %{BKY_CONTROLS_IF_MSG_THEN} ",
		args0: [{ type: "input_value", name: "IF0", check: "Boolean" }],
		message1: "%1",
		args1: [{ type: "input_statement", name: "DO0" }],
		previousStatement: null,
		nextStatement: null,
		style: "loop_blocks",
		helpUrl: "%{BKY_CONTROLS_IF_HELPURL}",
		mutator: "controls_if_mutator",
		extensions: ["controls_if_tooltip"],
		test: testStatement("general"),
	},
	{
		type: "controls_if_if",
		message0: "%{BKY_CONTROLS_IF_IF_TITLE_IF}",
		nextStatement: null,
		enableContextMenu: false,
		style: "loop_blocks",
		tooltip: "%{BKY_CONTROLS_IF_IF_TOOLTIP}",
	},
	{
		type: "controls_if_elseif",
		message0: "%{BKY_CONTROLS_IF_ELSEIF_TITLE_ELSEIF}",
		previousStatement: null,
		nextStatement: null,
		enableContextMenu: false,
		style: "loop_blocks",
		tooltip: "%{BKY_CONTROLS_IF_ELSEIF_TOOLTIP}",
	},
	{
		type: "controls_if_else",
		message0: "%{BKY_CONTROLS_IF_ELSE_TITLE_ELSE}",
		previousStatement: null,
		enableContextMenu: false,
		style: "loop_blocks",
		tooltip: "%{BKY_CONTROLS_IF_ELSE_TOOLTIP}",
	},
	{
		type: "leaphy_start",
		lastDummyAlign0: "CENTRE",
		message0: "%%{BKY_LEAPHY_START}",
		style: "leaphy_blocks",
		extensions: ["appendStatementInputStack"],
		isDeletable: false,
		helpUrl: "",
	},
];
