name: Build for ElimuPi

on:
  push:
    tags:
      - v*
    branches:
      - main
  workflow_dispatch: {}

jobs:
  build-elimu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Create ElimuPi env file
        working-directory: ./packages/client
        run: |
          cat << EOF > .env
          VITE_BACKEND_URL=""
          VITE_SENTRY_DSN=""
          VITE_SENTRY_SAMPLE_RATE="0.0"
          EOF
          echo "ENV=elimu" >> "$GITHUB_ENV"

      - name: Build application
        working-directory: ./packages/client
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          pnpm install
          pnpm build

      - name: Upload build files
        uses: actions/upload-artifact@v4
        working-directory: ./packages/client
        with:
          name: leaphyeasybloqs-${{ github.ref_name }}
          path: ./dist
