name: Deploy

on:
  push:
    branches:
      - pythonblocks
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Create env file
        run: |
          cat << EOF > .env
          VITE_BACKEND_URL="https://testleaphyeasybloqs.com"
          VITE_MATOMO_URL="https://leaphyeasybloqs.com/matomo/"
          VITE_MATOMO_SITE_ID="2"
          EOF
          echo "ENV=python" >> "$GITHUB_ENV"
          echo "STACK=leaphy-webbased-python" >> "$GITHUB_ENV"

      - name: Build application
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn --frozen-lockfile --prefer-offline
          yarn build

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/leaphy-robotics/leaphy-webbased-svelte/leaphy-webbased-svelte:${{ env.ENV }}

      - name: Redeploy
        run: |
          curl https://admin.leaphyeasybloqs.com/hooks/update-docker-image?stack=$STACK -H "X-Token: ${{ secrets.WEBHOOK_TOKEN }}"
