name: Deploy

on:
  push:
    tags:
      - v*
    branches:
      - main
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push TEST Docker image
        if: github.ref_type == 'branch'
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/leaphy-robotics/leaphy-webbased-svelte/leaphy-webbased-svelte:test

      - name: Redeploy TEST
        if: github.ref_type == 'branch'
        run: |
          curl https://admin.leaphyeasybloqs.com/hooks/update-docker-image?stack=leaphy-webbased-svelte -H "X-Token: ${{ secrets.WEBHOOK_TOKEN }}"

      - name: Clean up old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: "leaphy-webbased/leaphy-webbased-svelte"
          package-type: "container"
          min-versions-to-keep: 5
          delete-only-untagged-versions: "true"
