name: Deploy

on:
  push:
    tags:
      - v*
    branches:
      - main
  workflow_dispatch: {}

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Create TEST env file
        if: github.ref_type == 'branch'
        run: |
          cat << EOF > .env
          VITE_BACKEND_URL="https://testleaphyeasybloqs.com"
          VITE_MATOMO_URL="https://leaphyeasybloqs.com/matomo/"
          VITE_MATOMO_SITE_ID="2"
          VITE_SENTRY_DSN="${{ secrets.VITE_SENTRY_DSN }}"
          VITE_SENTRY_SAMPLE_RATE="1.0"
          VITE_RECORDINGS_API="https://recordings.leaphyeasybloqs.com"
          VITE_RECORDINGS_ADDRESS=".testleaphyeasybloqs.com"
          EOF
          echo "ENV=test" >> "$GITHUB_ENV"
          echo "STACK=leaphy-webbased-test" >> "$GITHUB_ENV"

      - name: Create PROD env file
        if: github.ref_type == 'tag'
        run: |
          cat << EOF > .env
          VITE_BACKEND_URL="https://leaphyeasybloqs.com"
          VITE_MATOMO_URL="https://leaphyeasybloqs.com/matomo/"
          VITE_MATOMO_SITE_ID="1"
          VITE_SENTRY_DSN="${{ secrets.VITE_SENTRY_DSN }}"
          VITE_SENTRY_SAMPLE_RATE="0.0"
          VITE_RECORDINGS_API="https://recordings.leaphyeasybloqs.com"
          VITE_RECORDINGS_ADDRESS=".leaphyeasybloqs.com"
          EOF
          echo "ENV=prod" >> "$GITHUB_ENV"
          echo "STACK=leaphy-webbased" >> "$GITHUB_ENV"
          echo "SENTRY_RELEASE=webbased-${{ github.ref_name }}" >> "$GITHUB_ENV"

      - name: Build application
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          export NODE_OPTIONS="--max-old-space-size=4096"
          yarn --frozen-lockfile --prefer-offline
          yarn build

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/leaphy-robotics/leaphy-webbased-svelte/leaphy-webbased-svelte:${{ env.ENV }}

      - name: Redeploy
        run: |
          curl https://admin.leaphyeasybloqs.com/hooks/update-docker-image?stack=$STACK -H "X-Token: ${{ secrets.WEBHOOK_TOKEN }}"

      - name: Clean up old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: "leaphy-webbased-svelte/leaphy-webbased-svelte"
          package-type: "container"
          min-versions-to-keep: 5
          delete-only-untagged-versions: "true"
